INSERT INTO productos (`id`, `link`, `nombre`, `precio`, `tipo`) VALUES
   (1, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/pandeyucas.jpg', 'Pandeyucas(Tradicionales y crocanticos)', 0, '(Entrada)'),
	(2, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/entrada%202%20(1).png', 'Arepas(De maíz pelao)', 0, '(Entrada)'),
	(3, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/cabro-1-400x250.jpg', 'Cabro Con Pepitoria(Yuca, Arepa y Ensalada)', 26000, '(Plato Fuerte)'),
	(4, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/pescado(act).jpg', 'Filete de Pescado(Arroz Blanco, Patacón y Ensalada)', 30000, '(Plato Fuerte)'),
	(5, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/sancocho-de-gallina(ACT).jpg', 'Sancocho de gallina(Arroz,aguacate y yuca)', 17000, '(Plato Fuerte)'),
	(6, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/pollo.jpg', 'Pollo asado(Yuca, Arepa, Papa y un delicioso ají)', 22000, '(Plato Fuerte)'),
	(7, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/sobrebarriga%20act.jpg', 'Sobrebarriga(Al Horno: Yuca, Arepa y Ensalada)', 24000, '(Plato Fuerte)'),
	(8, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/pechuga%20act.jpg', 'Pechuga a la plancha(Papa a la Francesa y Ensalada)', 17000, '(Plato Fuerte)'),
	(9, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/cazuela-act.jpg', 'Cazuela de Mariscos(Arroz Blanco y Patacón)', 34000, '(Plato Fuerte)'),
	(10, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/oreada%20act.png', 'Oreada(Arroz Blanco , Yuca, ensalada)', 19000, '(Plato Fuerte)'),
	(11, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/pavo%20relleno%20act.jpg', 'Pavo relleno(Pure de papa y ensalada agridulce)', 34000, '(Plato Fuerte)'),
	(12, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/arroz%20paisa.jpg', 'Arroz Paisa(patacones y aguacate)', 21000, '(Plato Fuerte)'),
	(13, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/ajiaco.jpg', 'Ajiaco Santareño(arroz blanco y aguacate)', 24000, '(Plato Fuerte)'),
	(15, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/Bandeja%20act.png', 'Bandeja Paisa', 17000, '(Plato Fuerte)'),
	(16, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/mute%20act.png', 'Mute(Yuca, Arroz y aguacate)', 14000, '(Plato Fuerte)'),
	(17, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/comidas/arroz-pollo.jpg', 'Arroz Con Pollo(papas a la Francesa y aguacate', 14000, '(Plato Fuerte)'),
	(18, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/pandeyucas.jpg', 'Pandeyucas(Tradicionales y crocanticos)', 6000, '(Adicionales)'),
	(19, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/entrada%202%20(1).png', 'Arepas(De maíz pelao)', 8000, '(Adicionales)'),
	(20, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/c.jpg', 'Hormigas Culonas(Platillo  exquisito (30gr))', 12000, '(Adicionales)'),
	(21, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/Papas%20fritas.jpg', 'Papas Fritas(Bien crujientes)', 7000, '(Adicionales)'),
	(22, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Adicionales/Captura%203.PNG', 'Patacones(De los mejores plátanos)', 7000, '(Adicionales)'),
	(23, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/cristal%20gas.jpg', 'Agua Cristal con gas', 1800, '(Bebidas)'),
	(24, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/cristal.png', 'Agua Cristal', 1200, '(Bebidas)'),
	(25, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/brisa%20manzana.jpg', 'Agua Manzana', 2300, '(Bebidas)'),
	(26, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/aguapanela.jpg', 'Aguapanela 1,5 lts', 1800, '(Bebidas)'),
	(27, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/pony.jpg', 'Pony Malta 1.5 lts', 3000, '(Bebidas)'),
	(28, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/coca%20cola.jpg', 'Cocacola 1.5 lts', 3500, '(Bebidas)'),
	(29, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/bebidas.jpg', 'Combo :Sprit,Cocacola,Fanta', 6000, '(Bebidas)'),
	(30, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/colombiana.jpg', 'Colombiana Postobon 1.5 lts', 3000, '(Bebidas)'),
	(31, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/gaseosa_kola_postobon.png', 'Kola Postobon 1.5 lts', 3000, '(Bebidas)'),
	(32, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/manza.jpg', 'Manzana Postobon 3lts', 6000, '(Bebidas)'),
	(33, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/naranja.jpg', 'Naranja Postobon 1.5 lts', 3000, '(Bebidas)'),
	(34, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/uva.jpg', 'Uva Postobon 1.5 lts', 3000, '(Bebidas)'),
	(35, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/seven%20up.png', 'Seven up Postobon 3lts', 6000, '(Bebidas)'),
	(36, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/hit%20mango.jpg', 'Hit mango', 2700, '(Bebidas)'),
	(37, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/hit%20mora.jpg', 'Hit Mora', 2700, '(Bebidas)'),
	(38, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/hot%20tropical.jpg', 'Hit Tropical', 2700, '(Bebidas)'),
	(39, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/jugos%20naturales.jpg', 'Jugos Naturales', 2100, '(Bebidas)'),
	(40, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/limonada.jpg', 'Limonada Natural', 2500, '(Bebidas)'),
	(41, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/lulada.jpg', 'Lulada', 2500, '(Bebidas)'),
	(42, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/aguila-cerveza.png', 'Cerveza Aguila', 3000, '(Bebidas)'),
	(43, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/black.png', 'Club Colombia  black', 7000, '(Bebidas)'),
	(44, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/dorada.png', 'Club Colombia Dorada', 7000, '(Bebidas)'),
	(45, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/COSTE%c3%91A.jpg', 'Cerveza Costeña ', 65000, '(Bebidas)'),
	(46, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/poker-x400.png', 'Cerveza Poker', 3000, '(Bebidas)'),
	(47, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/bebidas/heineken.jpg', 'Heineken ', 2500, '(Bebidas)'),
	(48, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/combo%201.jpg', 'Combo plato típico (Carne Oreada,Cabro,Rellena,Chorizo,Pepitoria,Arepa,Yuca y Ensalada)',43900, '(Especiales)'),
	(49, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/combo%203.png', 'Combo fritanga mediana (Chorizo,Rellena,Lomo de Cerdo,Costillitas de Cerdo,Chicharrón,Papa criolla y Maduro)', 36900, '(Especiales)'),
	(50, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/champagne%20vino%20espumoso%2073000.png', 'Champagne vino espumoso ideal para tus momentos especiales)', 73000, '(Especiales)'),
	(51, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/champa%c3%b1a.jpg', 'Champagne smirnoft (Champagne con sabores a naranja y lulo)', 45000, '(Especiales)'),
	(52, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/Champa%c3%b1a%20Francesa%20Moet%20&%20chandon%20Brut%20imperial.png', 'Champaña Francesa Moet & chandon Brut imperial', 273900, '(Especiales)'),
	(53, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/maipo%20vino%20tinto%20cabernet%20sauvignon.jpg', 'Maipo Vino tinto cabernet sauvignon', 73000, '(Especiales)'),
	(54, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/vino-tinto-montes-classic-series-merlot.jpg', 'Vino tinto merlot', 57000, '(Especiales)'),
	(55, 'https://el-sabor-de-nuestra-tierra.000webhostapp.com/imagenes/Especiales/Vinos-blanco_santa%20helena.jpg', 'Vino blanco Santa Helena', 38650, '(Especiales)');	
